- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: us-east-1

- name: Login to ECR
  run: |
    aws ecr get-login-password --region us-east-1 \
    | docker login --username AWS --password-stdin 535462128585.dkr.ecr.us-east-1.amazonaws.com

- name: Build Image
  run: |
    docker build -t app .

- name: Tag Image
  run: |
    docker tag app:latest 535462128585.dkr.ecr.us-east-1.amazonaws.com/app:latest

- name: Push Image
  run: |
    docker push 535462128585.dkr.ecr.us-east-1.amazonaws.com/app:latest
